### ISSUE TITLE
Setting ~/.okta/okta.yaml proxy values to `null` causes tests to fail

### ISSUE THREAD

**Issue by bdemers** [okta/okta-sdk-java#210]
```yml
   proxy:
      port: null
      host: null
      username: null
      password: null
```

`com.okta.sdk.impl.client.DefaultClientBuilderTest.testConfigureProxy` fails if the proxy is set to `null` (or set at all)

1.) null values should be ignored from the `okta.yaml` file
2.) this file should likely be mocked to NOT cause issues with the UTs
